@include('admin.layouts.header')
    @yield('admin-dashboard-section')
    @yield('admin-students-section')
    @yield('admin-teachers-section')
    @yield('admin-attendence-section')
    @yield('admin-assignment-section')
    @yield('admin-messages-section')
@include('admin.layouts.footer')
